spring.application.name=e-commerce

# 1. Configuración Fuente De Datos 
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db3?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# 2. Driver Específico 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Configuración Seguridad JWT (Clave + Expiración Del Token)
jwt.secret=clave-secreta-uade-ecommerce-grupo6-jueves-noche-2025
jwt.expiration-ms=86400000
